Pig Stack Trace
---------------
ERROR 1066: Unable to open iterator for alias farthest_events. Backend error : Vertex failed, vertexName=scope-75, vertexId=vertex_1492444588459_0001_1_00, diagnostics=[Task failed, taskId=task_1492444588459_0001_1_00_000005, diagnostics=[TaskAttempt 0 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
], TaskAttempt 1 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
], TaskAttempt 2 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
], TaskAttempt 3 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
]], Vertex did not succeed due to OWN_TASK_FAILURE, failedTasks:1 killedTasks:6, Vertex vertex_1492444588459_0001_1_00 [scope-75] killed/failed due to:null]
Vertex killed, vertexName=scope-107, vertexId=vertex_1492444588459_0001_1_04, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1492444588459_0001_1_04 [scope-107] killed/failed due to:null]
Vertex killed, vertexName=scope-96, vertexId=vertex_1492444588459_0001_1_03, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1492444588459_0001_1_03 [scope-96] killed/failed due to:null]
Vertex killed, vertexName=scope-94, vertexId=vertex_1492444588459_0001_1_02, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1492444588459_0001_1_02 [scope-94] killed/failed due to:null]
Vertex killed, vertexName=scope-84, vertexId=vertex_1492444588459_0001_1_01, diagnostics=[Vertex received Kill while in RUNNING state., Vertex did not succeed due to OTHER_VERTEX_FAILURE, failedTasks:0 killedTasks:1, Vertex vertex_1492444588459_0001_1_01 [scope-84] killed/failed due to:null]
DAG did not succeed due to VERTEX_FAILURE. failedVertices:1 killedVertices:4

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1066: Unable to open iterator for alias farthest_events. Backend error : Vertex failed, vertexName=scope-75, vertexId=vertex_1492444588459_0001_1_00, diagnostics=[Task failed, taskId=task_1492444588459_0001_1_00_000005, diagnostics=[TaskAttempt 0 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
], TaskAttempt 1 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
], TaskAttempt 2 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
], TaskAttempt 3 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
]], Vertex did not succeed due to OWN_TASK_FAILURE, failedTasks:1 killedTasks:6, Vertex vertex_1492444588459_0001_1_00 [scope-75] killed/failed due to:null]
Vertex killed, vertexName=scope-107, vertexId=vertex_1492444588459_0001_1_04, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1492444588459_0001_1_04 [scope-107] killed/failed due to:null]
Vertex killed, vertexName=scope-96, vertexId=vertex_1492444588459_0001_1_03, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1492444588459_0001_1_03 [scope-96] killed/failed due to:null]
Vertex killed, vertexName=scope-94, vertexId=vertex_1492444588459_0001_1_02, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1492444588459_0001_1_02 [scope-94] killed/failed due to:null]
Vertex killed, vertexName=scope-84, vertexId=vertex_1492444588459_0001_1_01, diagnostics=[Vertex received Kill while in RUNNING state., Vertex did not succeed due to OTHER_VERTEX_FAILURE, failedTasks:0 killedTasks:1, Vertex vertex_1492444588459_0001_1_01 [scope-84] killed/failed due to:null]
DAG did not succeed due to VERTEX_FAILURE. failedVertices:1 killedVertices:4
	at org.apache.pig.PigServer.openIterator(PigServer.java:1009)
	at org.apache.pig.tools.grunt.GruntParser.processDump(GruntParser.java:747)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:376)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:231)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:206)
	at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:81)
	at org.apache.pig.Main.run(Main.java:630)
	at org.apache.pig.Main.main(Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: org.apache.tez.dag.api.TezException: Vertex failed, vertexName=scope-75, vertexId=vertex_1492444588459_0001_1_00, diagnostics=[Task failed, taskId=task_1492444588459_0001_1_00_000005, diagnostics=[TaskAttempt 0 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
], TaskAttempt 1 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
], TaskAttempt 2 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
], TaskAttempt 3 failed, info=[Error: Failure while running task:org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: Local Rearrange[tuple]{tuple}(false) - scope-78	->	 scope-84 Operator Key: scope-78): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.runPipeline(PigProcessor.java:376)
	at org.apache.pig.backend.hadoop.executionengine.tez.runtime.PigProcessor.run(PigProcessor.java:241)
	at org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:337)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:179)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable$1.run(TezTaskRunner.java:171)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:171)
	at org.apache.tez.runtime.task.TezTaskRunner$TaskRunnerCallable.callInternal(TezTaskRunner.java:167)
	at org.apache.tez.common.CallableWithNdc.call(CallableWithNdc.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: New For Each(false,true)[tuple] - scope-83 Operator Key: scope-83): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:256)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 17 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: ReservoirSample - scope-80 Operator Key: scope-80): org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POReservoirSample.getNextTuple(POReservoirSample.java:97)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 19 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: mostmiles2atwaters: Local Rearrange[tuple]{double}(false) - scope-76	->	 scope-94 Operator Key: scope-76): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:314)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POLocalRearrange.getNextTuple(POLocalRearrange.java:287)
	at org.apache.pig.backend.hadoop.executionengine.tez.plan.operator.POLocalRearrangeTez.getNextTuple(POLocalRearrangeTez.java:127)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 21 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: datafu.pig.geo.HaversineDistInMiles [datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float]
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:354)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNextDouble(POUserFunc.java:390)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.getNext(PhysicalOperator.java:343)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.processPlan(POForEach.java:404)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POForEach.getNextTuple(POForEach.java:321)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:305)
	... 24 more
Caused by: java.io.IOException: datafu.pig.geo.HaversineDistInMiles(java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double): argument type mismatch [#3]; expected java.lang.Double, got java.lang.Float
	at datafu.pig.util.SimpleEvalFunc.exec(SimpleEvalFunc.java:160)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.expressionOperators.POUserFunc.getNext(POUserFunc.java:326)
	... 29 more
]], Vertex did not succeed due to OWN_TASK_FAILURE, failedTasks:1 killedTasks:6, Vertex vertex_1492444588459_0001_1_00 [scope-75] killed/failed due to:null]
Vertex killed, vertexName=scope-107, vertexId=vertex_1492444588459_0001_1_04, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1492444588459_0001_1_04 [scope-107] killed/failed due to:null]
Vertex killed, vertexName=scope-96, vertexId=vertex_1492444588459_0001_1_03, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1492444588459_0001_1_03 [scope-96] killed/failed due to:null]
Vertex killed, vertexName=scope-94, vertexId=vertex_1492444588459_0001_1_02, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1492444588459_0001_1_02 [scope-94] killed/failed due to:null]
Vertex killed, vertexName=scope-84, vertexId=vertex_1492444588459_0001_1_01, diagnostics=[Vertex received Kill while in RUNNING state., Vertex did not succeed due to OTHER_VERTEX_FAILURE, failedTasks:0 killedTasks:1, Vertex vertex_1492444588459_0001_1_01 [scope-84] killed/failed due to:null]
DAG did not succeed due to VERTEX_FAILURE. failedVertices:1 killedVertices:4
	at org.apache.pig.tools.pigstats.tez.TezPigScriptStats.accumulateStats(TezPigScriptStats.java:198)
	at org.apache.pig.backend.hadoop.executionengine.tez.TezJob.run(TezJob.java:243)
	at org.apache.pig.backend.hadoop.executionengine.tez.TezLauncher$1.run(TezLauncher.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
================================================================================
